name: Code Review with Gemini

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version

      - name: Install dependencies
        run: |
          bundle install
          gem install rubocop # Ensure rubocop is installed

      - name: Fetch Pull Request Code
        id: pr_code
        run: |
          # Fetch the pull request code from GitHub API
          PR_FILES=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files")

          echo "::set-output name=pr_files::$PR_FILES"

      - name: Analyze Code with Gemini and RuboCop
        id: gemini_review
        run: |
          # Send the code to Gemini for analysis
          ruby analyze_with_gemini.rb "${{ steps.pr_code.outputs.pr_files }}"

      - name: Post review comment on PR
        run: |
          PR_COMMENT=$(cat gemini_feedback.txt)
          curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{\"body\": \"$PR_COMMENT\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
